language: java

deploy:
  provider: heroku
  app: agen-api
  username: brunohallef@gmail.com
  password: 91696192Eu

#deploy:
#  provider: heroku
#  api_key: 5c0a4dd5-7528-4761-b53d-fb9cb9f72bba
#  app: agen-api